"""
Django settings for meu_projeto project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8d7vpew^#8s0s68^0sbfni7&8ov1v6b1+5g3-s&&zvv#9g=)rl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'usuarios',
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'meu_projeto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'meu_projeto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql', #tipo do banco
        'NAME': 'postgres', #nome do banco
        'USER': 'professor', #usuario
        'PASSWORD': 'professor', #senha
        'HOST': 'database-1.cofefkfnwzpi.us-east-1.rds.amazonaws.com', #Endereço de AWS
        'PORT': '5432' #Porta do PostgreSQL

    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# python --version
# Mostra a versão do Python instalada no computador.

# python -m pip install django
# Instala o Django no Python.

# python -m django --version
# Mostra a versão do Django instalada.

# python -m django startproject meu_projeto .
# Cria um projeto Django na pasta atual.
# O ponto final faz o projeto ser criado dentro da pasta que já está aberta.

# python manage.py runserver
# Inicia o servidor local do Django.
# Depois disso, o projeto abre em http://127.0.0.1:8000/

#É ESSE AQUI DEBAIXO P CRIAR AS PASTAS DAS TABELAS-------------------------------------------------------

# python manage.py startapp usuarios
# Cria um app chamado usuarios.
# Esse app guarda models, views, admin, migrations etc.

# python manage.py makemigrations
# Cria os arquivos de migration com base nas alterações feitas no models.py.
# É como preparar as mudanças do banco.

# python manage.py migrate
# Aplica as migrations no banco de dados.
# Ou seja, cria ou atualiza as tabelas no banco.

# python manage.py createsuperuser
# Cria um usuário administrador para acessar o painel /admin do Django.

# python manage.py shell
# Abre o terminal interativo do Django.
# Serve para testar comandos Python usando as configurações do projeto.

# from django.conf import settings
# Importa as configurações do Django dentro do shell.

# settings.DATABASES
# Mostra qual banco de dados o Django está usando.

# exit()
# Sai do shell interativo do Django.

# python manage.py diffsettings | findstr HOST
# Mostra configurações alteradas que tenham a palavra HOST.
# Usamos para conferir se o Django estava lendo o HOST correto do banco.

# python manage.py dbshell
# Tenta abrir o terminal do banco de dados configurado no Django.

