# Generated by Django 6.0.6 on 2026-06-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
